### ISSUE TITLE
A better way to manage inter-dependency between core and data packages

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodncore#102]
When changes are introduced in aodncore that require corresponding updates in aodndata, merging, building and deploying these changes becomes difficult (see e.g. https://github.com/aodn/python-aodndata/pull/51#issuecomment-397171379). New versions of each package are currently tested against the current **prod** version of the other package, so they always fail when such coordinated changes are required in _both_ packages.

We need to either:
* allow each packages to be tested (in Travis and in Jenkins) against the latest **build** (or **systest**) version of the other;
* test against _all_ available versions of the other package; or
* link the two Jenkins pipelines together somehow so the versions of both packages can be promoted together?

**Comment by mhidas** [comment]
I think we're managing this a bit better now, with Github Actions testing aodndata against all versions of aodncore (e.g. https://github.com/aodn/python-aodndata/actions/runs/481933049). We also haven't needed to make breaking changes in aodncore, and hopefully we can continue to avoid that.

So I think we can close this issue. @lwgordonimos Do you have any more thoughts on this?

**Comment by lwgordonimos** [comment]
Yes, I think the key here is to just not break the "API" any more. That is really the root cause of issues

An example of trying to avoid that is here, with adding deprecations warnings, which allow aodndata to be updated to the new patterns/methods, before removing the old methods: https://github.com/aodn/python-aodncore/pull/209/commits/8c1ec3be48817006c00b7fb9bb09b6c593ace358
