### ISSUE TITLE
handler should not fail on deleting objects not existing on S3

### ISSUE THREAD

**Issue by lbesnard** [aodn/python-aodncore#122]
For discussion

**Comment by mhidas** [comment]
I don't feel very strongly about this, but after chatting to @lwgordonimos I think it makes sense for the StorageBroker (S3 or otherwise) to raise an exception _by default_ in such a case. This _might_ catch bugs where and incorrect path has been passed to the delete method, _but only if that incorrect path is a non-existent file!_ It would not prevent an existing file from incorrectly being deleted due to a such a bug!

If raising an exception is the default behaviour, it would also be useful (e.g. for the Argo handler) to be able to override it, i.e. explicitly ask the broker to silently ignore such cases.

However, if this proves to be a bit complicated to implement, it might be easier to just leave it as it is, and always silently ignore non-existent delete files.

Either way, it would be good to make the behaviour the same for all StorageBroker types, S3, local file, etc...

**Comment by mhidas** [comment]
Ok, in the short term, this issue has been fixed by https://github.com/aodn/python-aodncore/commit/c76c3a8f78a186cb629979dc0ce01e2462e79b8f. Deletion of non-existent objects on S3 are silently ignored.

Is anyone keen to discuss a more rigorous solution to this in the longer term, or shall we just close this issue?

**Comment by lbesnard** [comment]
to me that's fine. it is as rigorous as the s3 behaviour

**Comment by ggalibert** [comment]
Happy to close this for now.

**Comment by lwgordonimos** [comment]
At a low level, it should behave identically to S3.

Unless there is a specific scenario which necessitates "strict" deletions(i.e. `rm` behaviour instead of `rm -f` behaviour), we should close this. It would need to be replicated somehow with the S3 broker in any case if we did need that.
