### ISSUE TITLE
Handle multiple file extension variants

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodncore#130]
I have a pipeline (ABOS_SOTS) set up to accept JPEG images. I've configured the "include_regexes" to accept a ".jpg" extension, but the uploaded files had ".JPG" (and possibly could have been ".jpeg" according to the [fountain of all knowledge](https://en.wikipedia.org/wiki/JPEG#JPEG_filename_extensions)). 

That config is easy to fix, but the handler is also relying on the [`FileType`](https://github.com/aodn/python-aodncore/blob/79e87d5a4c05d641b953d2c5b5d09ad164d5cb72/aodncore/pipeline/common.py#L95), which also expects ".jpg" only. Some of the other file types also have more than one commonly used extension (at least both lower- & upper-case). Can we make the `FileType` class more flexible to accommodate these variants?

**Comment by lwgordonimos** [comment]
That did occur to me at the time, and should be handled somehow. I think case-insensitivity is a no brainer, but the multiple extensions will need some thought.

The main issue is that it is currently possible to do a kind of forward/reverse lookup type thing.
For example, you can currently ask "for a given type, what is your extension" which returns a single extension. We'd need to make sure there was no code relying on this specific behaviour, and refactor that concept in "for a given type, what is your *list* of valid extensions".

Probably not a massive job, but I agree definitely something that should be done because it's not ideal currently.
